version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'
    volumes:
      - caregiverconnect-db:/var/lib/postgresql/data
      
  caregiver-backend:
    container_name: caregiver-backend
    image: caregiver-backend:latest
    build:
      context: ./provider-nodejs
    environment:
      HOSTNAME: ${HOSTNAME}
      SECRETKEY: ${SECRETKEY}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      GEOAPIFY_API_KEY: ${GEOAPIFY_API_KEY}
    depends_on:
      - postgres
    ports:
      - '8081:8081'

  caregiver:
    container_name: caregiver
    image: caregiver:latest
    build:
      context: .
    environment:
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres
      - caregiver-backend
    ports:
      - '80:8100'
volumes:
  caregiverconnect-db: