version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: caregiverconnect
    ports: 
      - '5432:5432'
    volumes:
      - caregiverconnect-db:/var/lib/postgresql/data
      
  caregiver-backend:
    container_name: caregiver-backend
    image: caregiver-backend:latest
    build:
      context: ./backend
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    volumes:
      - certs:/openssl/certs

  caregiver:
    container_name: caregiver
    image: caregiver:latest
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
      - caregiver-backend
    ports:
      - '80:8100'
    volumes:
      - certs:/openssl/certs
volumes:
  caregiverconnect-db:
  certs:
    external: true
    name: certs