version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - certs:/etc/nginx/certs/
    external_links:
      - caregiver
    networks:
      - caregiver-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'
    volumes:
      - caregiverconnect-db:/var/lib/postgresql/data
      - certs:/app/openssl/certs
    networks:
      - caregiver-network
      
  caregiver-backend:
    container_name: caregiver-backend
    image: caregiver-backend:latest
    build:
      context: ./provider-nodejs
    environment:
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    volumes:
      - certs:/app/openssl/certs
    networks:
      - caregiver-network

  caregiver:
    container_name: caregiver
    image: caregiver:latest
    build:
      context: .
    environment:
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres
      - caregiver-backend
    ports:
      - '8100:8100'
    volumes:
      - certs:/app/openssl/certs
    networks:
      caregiver-network:
        ipv4_address: 172.16.238.10

volumes:
  caregiverconnect-db:
  certs:
    external: true
    name: certs

networks:
  caregiver-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"