version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: caregiverconnect
    ports: 
      - '5432:5432'
    volumes:
      - caregiverconnect-db:/var/lib/postgresql/data
volumes:
  caregiverconnect-db:
