version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: ./nginx
    ports: 
      - '443:443'
      - '80:80'
    volumes:
      - certs:/etc/nginx/certs/
    networks:
      - caregiver-connect_default

volumes:
  certs:
    external: true
    name: certs
networks:
  caregiver-connect_default:
    name: caregiver-connect_default
    external: true