const sgMail = require("@sendgrid/mail")                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                               
function sendMsg(msg) {                                                                                                                                                                                                                                                        
    sgMail.setApiKey('')                                                                                                                                                                                  
    sgMail                                                                                                                                                                                                                                                                     
          .send(msg)                                                                                                                                                                                                                                                           
          .then(() => {                                                                                                                                                                                                                                                        
              console.log('Email sent')                                                                                                                                                                                                                                        
          })                                                                                                                                                                                                                                                                   
          .catch((error) => {                                                                                                                                                                                                                                                  
              console.error(error)                                                                                                                                                                                                                                             
          })                                                                                                                                                                                                                                                                   
}                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                               
module.exports = {                                                                                                                                                                                                                                                             
    sendMsg: sendMsg                                                                                                                                                                                                                                                           
} 